CREATE TABLE IF NOT EXISTS "restaurant" (
  "restaurant_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "owner_id" int NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar,
  "address" varchar,
  "opening_hours" varchar NOT NULL,
  "closing_hours" varchar NOT NULL,
  "img" varchar NULL,
  "is_active" bool NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "update_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "table" (
  "table_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "restaurant_id" int NOT NULL,
  "available" bool NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "update_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "reservation" (
  "reservation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "restaurant_id" int NOT NULL,
  "table_id" int NOT NULL,
  "reservation_data" date NOT NULL,
  "reservation_time" date NOT NULL,
  "costumer_name" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "update_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "user" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar NOT NULL,
  "telefono" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "update_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "owner" (
  "owner_id" SERIAL UNIQUE PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "consumer" (
  "consumer_id" SERIAL UNIQUE PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "category" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "restaurant_category" (
  "restaurant_category_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "restaurant_id" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "review" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "consumer_id" int NOT NULL,
  "comment" varchar NOT NULL,
  "grade" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "admin" (
  "admin_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL
);

ALTER TABLE "restaurant" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("owner_id");

ALTER TABLE "table" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("restaurant_id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("restaurant_id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("table_id") REFERENCES "table" ("table_id");

ALTER TABLE "owner" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");

ALTER TABLE "consumer" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");

ALTER TABLE "restaurant_category" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("restaurant_id");

ALTER TABLE "restaurant_category" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("category_id");

ALTER TABLE "review" ADD FOREIGN KEY ("consumer_id") REFERENCES "consumer" ("consumer_id");

ALTER TABLE "admin" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");
