networks:
  red_restaurante:
    driver: bridge
    ipam: 
      config:
        - subnet: 172.20.0.0/16

services:
  database:
    image: postgres
    networks:
      red_restaurante:
        ipv4_address: 172.20.0.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=air_restaurants
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
